### ISSUE TITLE
3 digit versions (5.1.3) without "v" fail

### ISSUE THREAD

**Issue by DALDEI** [Zoltu/Gradle.Plugin.Versioning#21] opened 2016-11-15 16:01 UTC
First off - **_thank you_**  this is just what I need to work around some very buggy 'features' in the Artifactory TeamCity plugin.

I found that a tag "5.1.3"  fails while "v5.1.3" or "5.1.3-tag.tag2" works
```

$ git tag -a -m "tagit" v5.1.4
$ git describe --long
v5.1.4-0-g1b00c93

$ gradle version
$ gradle version
:version
Version: 5.1.4-0

$ git tag -d 5.1.4
Deleted tag '5.1.4' (was a84b4c2)

$ git tag -a -m "tagit" 5.1.4
$ git describe --long
5.1.4-0-g1b00c93
$ gradle version

FAILURE: Build failed with an exception.

* Where:
Build file '/nexstra/artifactory-tc-bug/gradle-example-publish/build.gradle' line: 34

* What went wrong:
An exception occurred applying plugin request [id: 'com.zoltu.git-versioning', version: '2.0.30']
> Failed to apply plugin [id 'com.zoltu.git-versioning']
   > Git describe didn't return the expected format.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Not quite sure

Trying with

http://www.regexplanet.com/advanced/java/index.html

( http://fiddle.re/e1xqka )

These all match the semantic versioning (but with the tags, match[4] == null)
Why the v5.1.4 works (when it doesnt match simple) but 5.1.4 does not -- not sure.

Maybe the regex in groovy is different? 
This page is also helpful https://www.myregextester.com/index.php

**Comment by MicahZoltu** [comment] 2016-11-18 15:04
Ack, I just realized I didn't reply to this issue.  I'll try to read over it and get a response this evening.

**Comment by MicahZoltu** [comment] 2016-11-19 03:23
I'm unable to reproduce this bug.  :/  What I did:
1. Create a new gradle project with this build.gradle (tested with `gradle-2.13`):
   
   ```
   plugins {
       id "com.zoltu.git-versioning" version "2.0.30"
   }
   ```
2. `git tag -a -m "tagit" 5.1.4`
3. `./gradlew version`
   
   ```
   5.1.4-0
   :version
   Version: 5.1.4-0
   
   BUILD SUCCESSFUL
   
   Total time: 4.24 secs
   ```

What version of the plugin are you using?  Support for versions with no leading `v` is new, I think only in the latest version.

**Comment by MicahZoltu** [comment] 2016-11-23 22:01
v3.0 is out that supports any custom versioning scheme you like.  Check out the readme for details, or check out some example `build.gradle` files found in the tests.  Examples:
https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/test/kotlin/FunctionalTests.kt#L172-L177
https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/test/kotlin/FunctionalTests.kt#L208-L211
https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/test/kotlin/FunctionalTests.kt#L244-L247

**Comment by MicahZoltu** [comment] 2016-11-23 22:01
I'm going to close this issue for now, please do not hesitate to re-open it if you are still having trouble and I can try to help troubleshoot some more.

**Closed as completed by MicahZoltu** 2016-11-23 22:01 UTC
