### ISSUE TITLE
project.version Not available right away.

### ISSUE THREAD

**Issue by pluttrell** [Zoltu/Gradle.Plugin.Versioning#24] opened 2017-03-06 20:14 UTC
The `project.version` property isn't getting set until after Gradle's first pass, so setting other things as properties, end up getting set to `unspecified`. Do you have any suggestions for how to deal with this?

My specific use case is I want to tag docker images using `project.version` and I'm  using the id `"com.palantir.docker" version "0.12.0"` plugin and setting the tags as follows:

```
docker {
    tags project.version
}
```

**Comment by MicahZoltu** [comment] 2017-03-07 03:19
Hmm, `project.version` *should* be available around project startup.  I don't remember the Gradle lifecycle perfectly, but I think it is `project.afterEvaluate` executes after the project gradle files have all been parsed.  I believe there is a way in Gradle/Groovy to make it so your assignment of `project.version` to `docker.tags` is evaluated later, but I don't remember off-hand.  If you don't know a Gradle/Groovy expert I have had luck on the Gradle forums with this kind of question in the past.

Basically, you just need that assignment to occur *after* `project.afterEvaluate` in order for it to pick up the version number set by this plugin.  You may also want to talk to the author of the `docker` plugin and let them know that `project.version` isn't hard-coded and isn't available until after `project.afterEvaluate`, they may be able to give you feedback on whether you can lazily set `docker.tags`.  Assuming `docker.tags` isn't actually used until a task is run, you can do something like tell Gradle to assign `docker.tags` at a certain point in the project lifecycle that is a bit later (this is possible, but again I don't remember the syntax off-hand).

https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/main/kotlin/com/zoltu/gradle/plugin/GitVersioning.kt#L31

**Comment by pluttrell** [comment] 2017-03-09 08:44
@MicahZoltu Thanks for getting back to me.

I don't know Gradle's states well either. Nor do I know Kotlin yet, but I see `by lazy` on [L19 in that class](https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/main/kotlin/com/zoltu/gradle/plugin/GitVersioning.kt#L19) and wonder if that's the root cause.

As a work around I added a call to `ZoltuGitVersioning.versionInfo` near the top of my build script before I need `project.version` set and that appears to work for now.

**Comment by MicahZoltu** [comment] 2017-03-09 18:25
The `by lazy` means it will be initialized on first use and the result will be memoized for response to future calls.  This won't, in general, change the point at which the data is available since the first call will (synchronously) populate it.

That being said, looking over the code I do realize now that the lazy bit has a side effect, which is unfortunate.  I wonder if there is a better (sooner) place that it is safe to trigger that code?  Right now it is forcibly evaluated in `project.afterEvaluate` but apparently it can work earlier than that (as your workaround has shown).  I'm not sure if there is anything I can hook into that would ensure it is evaluated after all dependencies are loaded but before the gradle file finishes parsing?  I think I originally (maybe I'm mis-remembering) had it evaluate inline (when the plugin was applied) and ran into trouble which is why I made it lazy.  I suspect that I made it `by lazy` to deal with problems like this, where the user may need to use it in their script before `afterEvaluate` event.

I suspect that at the moment, your workaround is the best option for the time being.

**Comment by MicahZoltu** [comment] 2017-03-09 18:32
Ah, after looking at [this commit](https://github.com/Zoltu/Gradle.Plugin.Versioning/commit/b164bd19da3edb57f6fcccb745e82a5a3e6db658) I now remember why I changed it to not immediately initialize.  The problem is that the user can supply configuration that influences how the version is set (e.g., change the regex).  This improved customization and allowed the user to workaround some pretty significant bugs.  However, the plugin is necessarily always applied *before* the plugin is configured so I had to change it so the version would be set sometime *after* the plugin was configured.  By making it lazy, it would make it so that the user could choose to trigger (as you have done) when evaluation occurs, thereby giving the user an opportunity to configure things first.

I'm quite confident at this point that any solution that makes it so `version` is available during the initial pass of gradle script processing would also break other workflows.  The technique you have used is the appropriate solution to this problem, so I am going to close this issue for now.  If you can think of a better solution to this problem please let me know!  Also, if you would like to continue discussing this I'll continue to receive notifications on this issue and I don't mind re-opening it if that makes the most sense.

**Closed as completed by MicahZoltu** 2017-03-09 18:32 UTC

**Comment by pluttrell** [comment] 2017-03-09 20:38
Sounds good. Might be good to document this so that future users know the trade offs and make the appropriate decision based one their workflows.

**Comment by MicahZoltu** [comment] 2017-03-09 21:18
Good idea.  I added a note to the `NOTES` section of the Readme.
