### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by hanetzer** [Zoltu/Gradle.Plugin.Versioning#9] opened 2016-04-12 15:30 UTC
`org.eclipse.jgit.api.DescribeCommand.setLong(Z)Lorg/eclipse/jgit/api/DescribeCommand`
Not sure what's wrong here. [full log](https://gist.github.com/ntzrmtthihu777/5ea35aa6a851ba7149a4ba0b9ea66388)

**Comment by MicahZoltu** [comment] 2016-04-12 17:10
I haven't seen that error before.  Is the repository you are trying to use this with public so I can try to reproduce?  What version of Gradle are you using?  Are you using any other plugins that interact with git?

```
Caused by: java.lang.NoSuchMethodError: org.eclipse.jgit.api.DescribeCommand.setLong(Z)Lorg/eclipse/jgit/api/DescribeCommand;
    at com.zoltu.gradle.plugin.GitVersioning.getGitDescribeResults(GitVersioning.kt:53)
```

**Comment by MicahZoltu** [comment] 2016-04-12 17:21
The only thing I can think of that would cause that error is if the wrong version of `jgit` was used when the plugin tried to run.  The method in question `setLong` was added to `jgit` about a year ago in this commit: https://github.com/eclipse/jgit/commit/0e3ddea1b028836889fc13ad56b1dec5d5438fc9

I don't know exactly how Gradle plugins pull in dependencies, I assumed that they were hard-linked but maybe you have another plugin with an older version of `jgit` that is overriding the version this plugin references?  If `jgit` were missing entirely then the error would have occurred earlier in execution.

**Comment by MicahZoltu** [comment] 2016-04-12 17:21
If your source code isn't public, would you be able to share your `build.gradle` with me?  I may be able to poke through that and see if anything stands out and/or get a repro case created.

**Comment by hanetzer** [comment] 2016-04-12 18:13
there really isn't much to the build.gradle, and the source code will be public, but at the moment I'm just setting up

**Comment by MicahZoltu** [comment] 2016-04-12 20:26
``` groovy
buildscript {
    repositories {
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        // THIS LINE BELOW IS THE KEY
        classpath "org.eclipse.jgit:org.eclipse.jgit:4.3.0.201604071810-r"
        // THE LINE ABOVE IS THE KEY
        classpath "gradle.plugin.com.zoltu.gradle.plugin:git-versioning:2.0.12"
    }
}
```

It appears that the `net.minecraftforge.gradle.forge` or one of its dependencies plugin has bundled in an old version of `jgit` that doesn't have the `DescribeCommand.setLong()` method.  When the `git-versioning` plugin tries to call that method, it fails to find it because it sees the copy of `DescribeCommand` that is coming in via `net.minecraftforge.gradle.forge` or one of its dependencies.

By adding a reference to `org.eclipse.jgit` to the classpath, you can force gradle to use the version of the `DescribeCommand` class found in that dependency, rather than whatever is getting pulled in transitively.

**Comment by hanetzer** [comment] 2016-04-12 21:08
ok, question: What is this 'KEY' you're mentioning above?

**Comment by MicahZoltu** [comment] 2016-04-12 21:16
Sorry, I just meant that the line between the comments is what fixes the issue.  "Key to solving the problem"

**Comment by hanetzer** [comment] 2016-04-12 21:18
Ah gotcha. I'm filing a bug against MinecraftForge/Srg2Source#11

**Comment by MicahZoltu** [comment] 2016-04-12 21:24
To be clear, I'm not sure that is the issue, just a guess.  All I know it's that the plugin is pulling in an old version of jgit.

**Comment by MicahZoltu** [comment] 2016-05-01 00:01
I'm closing this issue out.  It appears that the linked MinecraftForge issue was resolved, so hopefully everything is now working for you!

**Closed as completed by MicahZoltu** 2016-05-01 00:01 UTC
